# Generated by Django 5.0.3 on 2024-05-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CHMED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_name', models.CharField(max_length=128, verbose_name='药物名称')),
                ('med_pic', models.CharField(blank=True, max_length=256, null=True, verbose_name='药物图片')),
                ('med_ingredience', models.CharField(max_length=512, verbose_name='成份')),
                ('med_character', models.CharField(max_length=512, verbose_name='性状')),
                ('med_use', models.CharField(max_length=1024, verbose_name='功能主治')),
                ('clinic', models.CharField(max_length=32, verbose_name='诊疗科')),
            ],
        ),
        migrations.CreateModel(
            name='WestMED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_name', models.CharField(max_length=128, verbose_name='药物名称')),
                ('med_pic', models.CharField(blank=True, max_length=256, null=True, verbose_name='药物图片')),
                ('med_ingredience', models.CharField(blank=True, max_length=512, null=True, verbose_name='成份')),
                ('med_use', models.CharField(blank=True, max_length=1024, null=True, verbose_name='功能主治')),
                ('med_warn', models.CharField(blank=True, max_length=1024, null=True, verbose_name='禁忌')),
            ],
        ),
    ]
